version: '3.7'
services:
    docker_mysql_db:
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        image: mysql:5.7
        volumes: 
            - .:/sql # contains the inital script to setup the db tables.
        restart: always
        ports: 
            - "3306:3306/tcp"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: setincanada
            MYSQL_USER: setincanada_user
            MYSQL_PASSWORD: "Setincanada_us3r!"